### ISSUE TITLE
Gelbe Meldung bei Domänen-Beitritt

### ISSUE THREAD

**Issue by aledjones** [simonfieberIT/Windows-Server-Installtool#1]
Stört nicht, sieht aber kacke aus, wenn man es präsentieren will.

Pls fix, thx.

**Comment by aledjones** [comment]
Oh, und eine Auswertung von Fehlern wäre schön, da ansonsten auch Fehler beim Beitritt als "erfolgreicher Beitritt" abgehandelt werden.

**Comment by si0nDE** [comment]
Die gelbe Meldung wurde gefixt und wird in den nächsten Tagen freigegeben.

Die Auswertung von Fehlern ist geplant und muss nur noch umgesetzt werden.
